parameters:
  cors.config:
      enabled: true
      # Specify allowed headers, like 'x-allowed-header'.
      allowedHeaders: ['x-csrf-token,authorization,content-type,accept,origin,x-requested-with']
      # Specify allowed request methods, specify ['*'] to allow all possible ones.
      allowedMethods: ['POST, GET, OPTIONS, DELETE, PUT, PATCH']
      # Configure requests allowed from specific origins.
      allowedOrigins: ['*']
      # Sets the Access-Control-Expose-Headers header.
      exposedHeaders: false
      # Sets the Access-Control-Max-Age header.
      maxAge: 1000
      # Sets the Access-Control-Allow-Credentials header.
      supportsCredentials: false
